#ifndef _ENUMERATIONS_H_
#define _ENUMERATIONS_H_


enum MessageType
{
	GAMEGROUP_ADDCHILD_OBJECT,
	GAMEGROUP_ADDCHILD_SWITCH,
	ADD_CHARACTER,
	SEND_MESSAGE_PLAYER1LEFT,
	SEND_MESSAGE_PLAYER1RIGHT,
	SEND_MESSAGE_GIVECHARACTER,
	SEND_MESSAGE_GIVELIVESWITCH,
	SEND_MESSAGE_GIVECATCHSWITCH,
	SEND_MESSAGE_LOSTINDEX,
	SEND_MESSAGE_UPDATESCOREWITHCATCH,
	SEND_MESSAGE_UPDATESCOREWITHLEVEL,
	SEND_MESSAGE_CREATECATCHABLE,
	SEND_MESSAGE_CLEARCATCHABLE,
	SEND_MESSAGE_LEFTKEYADD,
	SEND_MESSAGE_RIGHTKEYADD,
	SEND_CHARACTER
};



#endif