
///////////////////////////////////////////////////
// module name: mHiOsgCamera
// module creation date: 09-07-15
// Generated by hiFramework module frame Maker 1.0
///////////////////////////////////////////////////

#include "mHiOsgCamera.h"
#include "HiKernel/HiOSGRenderer.h"
#include "HiModules/enumerations.h"

using namespace HiModules;

mHiOsgCamera::mHiOsgCamera(HiKernel::HiXmlNode*xml)
{
}

mHiOsgCamera::~mHiOsgCamera()
{
}

bool mHiOsgCamera::HandleMessage(const HiKernel::HiTelegram& msg)
{
	
	return true;
	
}



void mHiOsgCamera::PostConfig()
{
	
	HiKernel::OSGRenderer->getViewer()->setCameraManipulator(new osgGA::TrackballManipulator());
}

void mHiOsgCamera::Render()
{
}

void mHiOsgCamera::Terminate()
{
}

void mHiOsgCamera::Update()
{
	//	NSLog(@"OsgCamera");
}

#ifndef HI_IOS4

extern "C" 
HI_DLLEXPORT mHiOsgCamera* HiLoadModule_mHiOsgCamera(HiKernel::HiXmlNode* xml)
{
	mHiOsgCamera *m = new mHiOsgCamera(xml);
	return m;
}

#endif