
///////////////////////////////////////////////////
// module name: mHiOsgCamera
// module creation date: 09-07-15
// Generated by hiFramework module frame Maker 1.0
///////////////////////////////////////////////////

#pragma once

#include "HiKernel/HiModule.h"
#include "HiKernel/HiFramework.h"

namespace HiModules 
{
	
	class HI_DLLEXPORT mHiOsgCamera : public HiKernel::HiModule
	{
	public:
		mHiOsgCamera(HiKernel::HiXmlNode*xml=NULL);                                   
		virtual ~mHiOsgCamera();
		
		bool HandleMessage(const HiKernel::HiTelegram& msg);
		void PostConfig();
		void Render();
		void Terminate();
		void Update();
		
		private :    
		
	};
}