/*
 *  enumerations.h
 *  iOSG
 *
 *  Created by rehomik on 09. 07. 07.
 *  Copyright 2009 IMRLAB. All rights reserved.
 *
 */
#pragma once

namespace HiModules
{
	enum MessageType
	{
		BAD_EFFECT_SOUND,
		GOOD_EFFECT_SOUND,
		IPHONE_TOUCHED,
		IPHONE_TOUCH_END,
		IPHONEINPUT_ONETOUCH_DOWN,
		IPHONEINPUT_ONETOUCH_UP,
		IPHONEINPUT_TWOTOUCH_DOWN,
		IPHONEINPUT_TWOTOUCH_UP,
		IPHONEINPUT_MOVETOUCH,
		MSG_SIZE,
		MSG_INVALID,
		GAMEGROUP_ADDCHILD_OBJECT,
		GAMEGROUP_ADDCHILD_SWITCH,
		SEND_MESSAGE_LOSTINDEX,
		SEND_MESSAGE_UPDATESCOREWITHCATCH,
		SEND_MESSAGE_UPDATESCOREWITHLEVEL,
		ADD_CHARACTER,
		SEND_MESSAGE_GIVECHARACTER,
		SEND_MESSAGE_GIVELIVESWITCH,
		SEND_MESSAGE_GIVECATCHSWITCH,
		SEND_MESSAGE_PLAYER1LEFT,
		SEND_MESSAGE_PLAYER1RIGHT,
		SEND_MESSAGE_CREATECATCHABLE,
		SEND_MESSAGE_CLEARCATCHABLE,
		
	};
}
