
///////////////////////////////////////////////////
// module name: mHiIPhoneInput
// module creation date: 09-07-09
// Generated by hiFramework module frame Maker 1.0
///////////////////////////////////////////////////

#if defined ( HI_IOS4 )

#pragma once

#include "HiKernel/HiModule.h"

@class EAGLView;
@class AccelerationGetter;

namespace HiModules 
{


	
		
	//class HiKernel::HiTelegram;
	
	class mHiIPhoneInput : public HiKernel::HiModule
	{	
	public:
		mHiIPhoneInput(HiKernel::HiXmlNode*xml=NULL);                                   
		virtual ~mHiIPhoneInput();     
		
		bool HandleMessage(const HiKernel::HiTelegram& msg);
		void PostConfig();
		void Update();
		void Render();
		void Terminate();
		
			
	private:
		AccelerationGetter* acceleration_getter_;
		
		EAGLView* m_EaglView;
		
		double                 acceleration_value_x_;
		double                 acceleration_value_y_;
		double                 acceleration_value_z_;
		
		//    double                  magnetic_heading_;
	};
}

#endif